### ISSUE TITLE
Use kleur instead of chalk

### ISSUE THREAD

**Issue by muuvmuuv** [rap2hpoutre/taskz#4]
I have recently seen this package called [kleur](https://github.com/lukeed/kleur) which is the same as chalk but with zero dependencies. It works a little different but is as nice as chalk. I think this would reduce the overall bundle size as you can see here: https://bundlephobia.com/result?p=taskz@1.3.0

**Comment by rap2hpoutre** [comment]
Thank you for your suggestion! Fixed via #9
