### ISSUE TITLE
Was Spinnies 0.5.0 bump never published?

### ISSUE THREAD

**Issue by erikmueller** [rap2hpoutre/taskz#5]
Hello, and sorry if I overlooked sth but it seems the indent fix (using a newer version of spinnies) was never published (as 1.3.1 or sth). Just noticed that 1.3.0 does not correctly indent.

**Comment by rap2hpoutre** [comment]
Woops! It seems I forgot to publish it. A new release has been released (2.0) thanks to you(!) in march.
